Anatomy3D: EngineTests.calculus.QuadraticFunctionTests Class Reference
EngineTests.calculus.QuadraticFunctionTests Class Reference
Public Member Functions
QuadraticFunctionTests (ITestOutputHelper testLogger)
void TestValueCalculation (float a0, float a1, float a2, float x, float expected)
Tests quadratic function evaluation in cases where the expected value is a number. This test passes if the actual result is relatively near the expected result (Near(FreedomOfFormFoundation.AnatomyEngine.Real,FreedomOfFormFoundation.AnatomyEngine.Real) for how near "relatively near" is).
void TestValueNaN (float a0, float a1, float a2, float x)
Tests quadratic function evaluation in cases where the expected value is NaN, which requires special comparison.
void TestDerivativesAt (float a0, float a1, float a2, float x, float atD0, float atD1, float atD2)
Tests evaluation of a function at derivatives from 0 to 4. Does not support expected NaN results. The 3rd and 4th derivatives of a quadratic function are always 0, so there is no parameter for this.
void TestSolve (float a0, float a1, float a2, float[] want)
Private Member Functions
bool Near (Real a, Real b, Real tolerance)
Helper method: are these numeric values relatively near each other?
bool Near (Real a, Real b)
Helper method: are these numeric values proportionally within 1e-5 of each other?
Private Attributes
readonly ITestOutputHelper testLogger
Detailed Description
Definition at line 11 of file QuadraticFunctionTests.cs.
Constructor & Destructor Documentation
QuadraticFunctionTests()
EngineTests.calculus.QuadraticFunctionTests.QuadraticFunctionTests (ITestOutputHelper testLogger) inline
Definition at line 16 of file QuadraticFunctionTests.cs.
         {
             this.testLogger = testLogger;
         }
Member Function Documentation
Near() [1/2]
bool EngineTests.calculus.QuadraticFunctionTests.Near (Real a, Real b) inline private
Helper method: are these numeric values proportionally within 1e-5 of each other?
Developer note: If 1e-5 turns out to be a bad default tolerance, change it, it's vaguely arbitrary.
Parameters
a
b
Returns
Definition at line 56 of file QuadraticFunctionTests.cs.
         {
             return Near(a, b, 1e-5);
         }
Near() [2/2]
bool EngineTests.calculus.QuadraticFunctionTests.Near (Real a, Real b, Real tolerance) inline private
Helper method: are these numeric values relatively near each other?
This is pretty much just wrapping a cast to Real and using its IsRelativelyNear algorithm.
Developer note: 0 isn't "relatively near" anything else because no amount of nonzero multiplication will get a nonzero value to zero. This is part of why I'm using "relatively near" here - I think unexpected transitions into or out of 0 will cause discontinuities and errors.
Parameters
a First value to compare.
b Second value to compare.
tolerance Proportional error allowed to still consider the elements near each other.
Returns
Whether the proportional difference between a and b is within the tolerance.
Definition at line 34 of file QuadraticFunctionTests.cs.
         {
             bool ret = a.IsRelativelyNear(b, tolerance);
             if (!ret)
             {
                 testLogger.WriteLine(
                     "Impending test failure: {0} is not near {1} (tolerance {2})",
                     a, b, tolerance
                 );
             }
             return ret;
         }
Referenced by EngineTests.calculus.QuadraticFunctionTests.Near(), EngineTests.calculus.QuadraticFunctionTests.TestDerivativesAt(), EngineTests.calculus.QuadraticFunctionTests.TestSolve(), and EngineTests.calculus.QuadraticFunctionTests.TestValueCalculation().
TestDerivativesAt()
void EngineTests.calculus.QuadraticFunctionTests.TestDerivativesAt (float a0, float a1, float a2, float x, float atD0, float atD1, float atD2) inline
Tests evaluation of a function at derivatives from 0 to 4. Does not support expected NaN results. The 3rd and 4th derivatives of a quadratic function are always 0, so there is no parameter for this.
Parameters
a0 Constant term in the quadratic function.
a1 Linear term in the quadratic function.
a2 Quadratic term in the quadratic function.
x Value of X to test at.
atD0 Expected value of the function (the 0th derivative) at x.
atD1 Expected value of the first derivative at x.
atD2 Expected value of the second derivative at x.
Definition at line 129 of file QuadraticFunctionTests.cs.
         {
             QuadraticFunction q = new QuadraticFunction(a0, a1, a2);
             Assert.NotNull(q);
             Assert.True(Near(q.GetNthDerivativeAt(x, 0), atD0));
             Assert.True(Near(q.GetNthDerivativeAt(x, 1), atD1));
             Assert.True(Near(q.GetDerivativeAt(x), atD1));
             Assert.True(Near(q.GetNthDerivativeAt(x, 2), atD2));
             Assert.Equal(q.GetNthDerivativeAt(x, 3), 0);
             Assert.Equal(q.GetNthDerivativeAt(x, 4), 0);
         }
TestSolve()
void EngineTests.calculus.QuadraticFunctionTests.TestSolve (float a0, float a1, float a2, float[] want) inline
Definition at line 144 of file QuadraticFunctionTests.cs.
         {
             IList<float> got = QuadraticFunction.Solve(a0, a1, a2).ToList();
             Assert.Equal(want.Length, got.Count);
             // There are no guarantees as to the order of values returned, so sort both sequences and compare items
             // at equal locations in the sorted sequence. Expect them all to match. We don't need to try any other
             // permutations of these lists to find out if there's some way they do match:
             //
             // If the smallest unmatched elements of each set are not adequately near each other, there is no way to
             // match the smaller of the two to any element in its other set. We have just compared it against the
             // smallest element in the other set, and found it to be too large. It cannot be too small, because we
             // are specifically considering the smaller element of the mismatched pair. Since the too-large element
             // was a smallest element of its set, all other elements are at least that large. Therefore, there is no
             // element small enough to match the smallest unmatched element between both sets, so the sets are unequal.
             // Backtracking does not help, because to find a smaller element of the opposite set, we must take it away
             // from its match to an element that is no larger than the one we are now matching (because all larger
             // elements are still in the unmatched portion of the set), and now _that_ element has the same problem
             // but worse.
             //
             // Therefore, there is no reason to attempt any other order than an element-by-element pairwise comparison
             // of the sorted sequences. ∎
             Array.Sort(want);
             int i = 0;
             var gotSorted = from c in got orderby c select c;
             foreach(float f in gotSorted)
             {
                 Assert.True(Near(want[i++], f));
             }
         }
TestValueCalculation()
void EngineTests.calculus.QuadraticFunctionTests.TestValueCalculation (float a0, float a1, float a2, float x, float expected) inline
Tests quadratic function evaluation in cases where the expected value is a number. This test passes if the actual result is relatively near the expected result (Near(FreedomOfFormFoundation.AnatomyEngine.Real,FreedomOfFormFoundation.AnatomyEngine.Real) for how near "relatively near" is).
Parameters
a0 Constant term in quadratic function.
a1 Linear term in quadratic function.
a2 Quadratic term in quadratic function.
x Value to test at.
expected
Definition at line 83 of file QuadraticFunctionTests.cs.
         {
             QuadraticFunction q = new QuadraticFunction(a0, a1, a2);
             Assert.NotNull(q);
             Assert.True(Near(expected, q.GetValueAt(x)));
             Assert.True(Near(expected, q.GetNthDerivativeAt(x, 0)));
         }
TestValueNaN()
void EngineTests.calculus.QuadraticFunctionTests.TestValueNaN (float a0, float a1, float a2, float x) inline
Tests quadratic function evaluation in cases where the expected value is NaN, which requires special comparison.
Note that, in IEEE floating point, 0 is "zero-ish", so multiplying infinity by a zero is numerically undefined, represented as NaN. Cases multiplying infinity by zero wind up here.
Parameters
a0 Constant term in quadratic function.
a1 Linear term in quadratic function.
a2 Quadratic term in quadratic function.
x Value to test at.
Definition at line 104 of file QuadraticFunctionTests.cs.
         {
             QuadraticFunction q = new QuadraticFunction(a0, a1, a2);
             Assert.NotNull(q);
             Assert.True(float.IsNaN(q.GetValueAt(x)));
             Assert.True(float.IsNaN(q.GetNthDerivativeAt(x, 0)));
         }
Member Data Documentation
testLogger
readonly ITestOutputHelper EngineTests.calculus.QuadraticFunctionTests.testLogger private
Definition at line 14 of file QuadraticFunctionTests.cs.
Referenced by EngineTests.calculus.QuadraticFunctionTests.Near(), and EngineTests.calculus.QuadraticFunctionTests.QuadraticFunctionTests().
The documentation for this class was generated from the following file:
EngineTests/calculus/QuadraticFunctionTests.cs