Anatomy3D: EngineTests.FunctionBackedContinuousMapTests Class Reference
EngineTests.FunctionBackedContinuousMapTests Class Reference
Public Member Functions
void TestBasicFunctionality ()
void TestCasts ()
void TestThen ()
void TestCompose ()
Static Private Member Functions
static int TimesTwo (int x)
Detailed Description
Definition at line 23 of file FunctionBackedContinuousMapTests.cs.
Member Function Documentation
TestBasicFunctionality()
void EngineTests.FunctionBackedContinuousMapTests.TestBasicFunctionality () inline
Definition at line 26 of file FunctionBackedContinuousMapTests.cs.
         {
             var c = new FunctionBackedContinuousMap<int, int>(x => x + 1);
             Assert.NotNull(c);
             Assert.Equal(5, c.GetValueAt(4));
             Assert.Equal(3, c.F(2));
             Assert.IsAssignableFrom<ContinuousMap<int, int>>(c);
         }
TestCasts()
void EngineTests.FunctionBackedContinuousMapTests.TestCasts () inline
Definition at line 39 of file FunctionBackedContinuousMapTests.cs.
         {
             // C# can't go straight from the function to a ContinuousMap, because technically it's already a cast to
             // become a Func (or any delegate type), double implicit casts are not considered when looking for
             // conversion operators, and there's no way to specify "method set" as the source for an implicit cast.
             // Oh well. Still, if we explicitly cast to Func, our conversion works:
             ContinuousMap<int, int> c = (Func<int, int>) TimesTwo;
             Assert.NotNull(c);
             Assert.Equal(10, c.GetValueAt(5));
             Assert.IsAssignableFrom<FunctionBackedContinuousMap<int, int>>(c);
             Assert.Equal(4, ((FunctionBackedContinuousMap<int, int>) c).F(2));
             FunctionBackedContinuousMap<int, int> d = (Func<int, int>) TimesTwo;
             Assert.NotNull(d);
             Assert.Equal(10, d.GetValueAt(5));
             Assert.Equal(4, d.F(2));
             Assert.IsAssignableFrom<ContinuousMap<int, int>>(d);
             var e = (ContinuousMap<int, int>) TimesTwo;
             Assert.NotNull(e);
             Assert.Equal(10, e.GetValueAt(5));
             Assert.IsAssignableFrom<FunctionBackedContinuousMap<int, int>>(e);
             Assert.Equal(4, ((FunctionBackedContinuousMap<int, int>) e).F(2));
         }
TestCompose()
void EngineTests.FunctionBackedContinuousMapTests.TestCompose () inline
Definition at line 73 of file FunctionBackedContinuousMapTests.cs.
         {
             ContinuousMap<int, int> c = ((ContinuousMap<int, int>)TimesTwo).Compose((int x) => x + 1);
             Assert.NotNull(c);
             Assert.Equal(16, c.GetValueAt(7));
         }
TestThen()
void EngineTests.FunctionBackedContinuousMapTests.TestThen () inline
Definition at line 65 of file FunctionBackedContinuousMapTests.cs.
         {
             ContinuousMap<int, int> c = ((ContinuousMap<int, int>)TimesTwo).Then(x => (x + 1));
             Assert.NotNull(c);
             Assert.Equal(expected: 15, actual: c.GetValueAt(7));
         }
TimesTwo()
static int EngineTests.FunctionBackedContinuousMapTests.TimesTwo (int x) static private
Referenced by EngineTests.FunctionBackedContinuousMapTests.TestCasts(), EngineTests.FunctionBackedContinuousMapTests.TestCompose(), and EngineTests.FunctionBackedContinuousMapTests.TestThen().
The documentation for this class was generated from the following file:
EngineTests/calculus/FunctionBackedContinuousMapTests.cs