Anatomy3D: FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment Class Reference
FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment Class Reference
A LineSegment defines a straight line in 3D space, with a start and end point.
Public Member Functions
LineSegment (dvec3 start, dvec3 end)
LineSegment (dvec3 start, dvec3 end, dvec3 normal)
override dvec3 GetPositionAt (double t)
Returns the position in 3D space of the curve based on the parametric variable t .
override dvec3 GetTangentAt (double t)
Returns the tangent vector of the curve based on the parametric variable t .
override dvec3 GetNormalAt (double t)
Returns the normal vector of the curve based on the parametric variable t .
override dvec3 GetStartPosition ()
Returns the position in 3D space of the start point of the curve. Should return the same value as getPositionAt(0.0).
override dvec3 GetEndPosition ()
Returns the position in 3D space of the end point of the curve. Should return the same value as getPositionAt(1.0).
Public Member Functions inherited from FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve
abstract dvec3 GetPositionAt (double t)
Returns the position in 3D space of the curve based on the parametric variable t .
abstract dvec3 GetTangentAt (double t)
Returns the tangent vector of the curve based on the parametric variable t .
abstract dvec3 GetNormalAt (double t)
Returns the normal vector of the curve based on the parametric variable t .
virtual dvec3 GetBinormalAt (double t)
Returns the binormal vector of the curve based on the parametric variable t .
virtual dvec3 GetStartPosition ()
Returns the position in 3D space of the start point of the curve. Should return the same value as getPositionAt(0.0).
virtual dvec3 GetEndPosition ()
Returns the position in 3D space of the end point of the curve. Should return the same value as getPositionAt(1.0).
override dvec3 GetValueAt (double t)
Public Member Functions inherited from FreedomOfFormFoundation.AnatomyEngine.Calculus.ContinuousMap< double, dvec3 >
abstract TOut GetValueAt (TIn t)
Private Attributes
dvec3 _start
dvec3 _end
dvec3 _normal
Additional Inherited Members
Static Public Member Functions inherited from FreedomOfFormFoundation.AnatomyEngine.Calculus.ContinuousMap< double, dvec3 >
static implicit operator ContinuousMap< TIn, TOut > (TOut m)
static implicit operator ContinuousMap< TIn, TOut > (Func< TIn, TOut > f)
Detailed Description
A LineSegment defines a straight line in 3D space, with a start and end point.
Definition at line 24 of file LineSegment.cs.
Constructor & Destructor Documentation
LineSegment() [1/2]
FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.LineSegment (dvec3 start, dvec3 end) inline
Definition at line 30 of file LineSegment.cs.
        {
            _start = start;
            _end = end;
            // No normal supplied, pick arbitrary normal vector:
            _normal = VectorUtilities.InventNormal(end - start);
        }
LineSegment() [2/2]
FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.LineSegment (dvec3 start, dvec3 end, dvec3 normal) inline
Definition at line 39 of file LineSegment.cs.
        {
            _start = start;
            _end = end;
            // Ensure that the normal is truly perpendicular to the tangent vector:
            dvec3 tangent = (end - start).Normalized;
            dvec3 up = dvec3.Cross(tangent, normal).Normalized;
            _normal = dvec3.Cross(up, tangent).Normalized;
        }
Member Function Documentation
GetEndPosition()
override dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetEndPosition () inline virtual
Returns the position in 3D space of the end point of the curve. Should return the same value as getPositionAt(1.0).
Reimplemented from FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.
Definition at line 78 of file LineSegment.cs.
        {
            return _end;
        }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.SymmetricCylinder.RayIntersect().
GetNormalAt()
override dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetNormalAt (double t) inline virtual
Returns the normal vector of the curve based on the parametric variable t .
Implements FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.
Definition at line 65 of file LineSegment.cs.
        {
            // The tangent vector is always in the direction of the line:
            return _normal; // TODO: Should this be normalized, or is length information useful?
        }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.SymmetricCylinder.RayIntersect().
GetPositionAt()
override dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetPositionAt (double t) inline virtual
Returns the position in 3D space of the curve based on the parametric variable t .
Implements FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.
Definition at line 51 of file LineSegment.cs.
        {
            // Simply return the linearly interpolated position between `start` and `end`:
            return t*_end + (1.0-t)*_start;
        }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.SymmetricCylinder.RayIntersect().
GetStartPosition()
override dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetStartPosition () inline virtual
Returns the position in 3D space of the start point of the curve. Should return the same value as getPositionAt(0.0).
Reimplemented from FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.
Definition at line 72 of file LineSegment.cs.
        {
            return _start;
        }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.SymmetricCylinder.RayIntersect().
GetTangentAt()
override dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetTangentAt (double t) inline virtual
Returns the tangent vector of the curve based on the parametric variable t .
Implements FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.
Definition at line 58 of file LineSegment.cs.
        {
            // The tangent vector is always in the direction of the line:
            return _end - _start; // TODO: Should this be normalized, or is length information useful?
        }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.SymmetricCylinder.RayIntersect().
Member Data Documentation
_end
dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment._end private
Definition at line 27 of file LineSegment.cs.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetEndPosition(), FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetPositionAt(), FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetTangentAt(), and FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.LineSegment().
_normal
dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment._normal private
Definition at line 28 of file LineSegment.cs.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetNormalAt(), and FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.LineSegment().
_start
dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment._start private
Definition at line 26 of file LineSegment.cs.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetPositionAt(), FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetStartPosition(), FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.GetTangentAt(), and FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment.LineSegment().
The documentation for this class was generated from the following file:
engine/geometry/LineSegment.cs