Anatomy3D: EngineTests.calculus.MutablePiecewiseInterpolatedCurveTests Class Reference
EngineTests.calculus.MutablePiecewiseInterpolatedCurveTests Class Reference
Public Member Functions
void TestUnchangingCurveWithPoints (IEnumerable< LiteralResultPoint > pointsEnumerable)
void TestChangingCurveWithPoints (IEnumerable< LiteralResultPoint > pointsEnumerable)
Static Public Member Functions
static IEnumerable< object[]> RandomPointLists ()
Static Private Member Functions
static IEnumerable< LiteralResultPoint > RandomPoints (int pointCount)
static LiteralResultPoint RandomPoint ()
Static Private Attributes
static readonly Random Rand = new Random()
Detailed Description
Definition at line 156 of file MutablePiecewiseInterpolatedCurveTests.cs.
Member Function Documentation
RandomPoint()
static LiteralResultPoint EngineTests.calculus.MutablePiecewiseInterpolatedCurveTests.RandomPoint () static private
RandomPointLists()
static IEnumerable< object[]> EngineTests.calculus.MutablePiecewiseInterpolatedCurveTests.RandomPointLists () static
RandomPoints()
static IEnumerable< LiteralResultPoint > EngineTests.calculus.MutablePiecewiseInterpolatedCurveTests.RandomPoints (int pointCount) static private
Referenced by EngineTests.calculus.MutablePiecewiseInterpolatedCurveTests.RandomPointLists(), and EngineTests.calculus.MutablePiecewiseInterpolatedCurveTests.TestChangingCurveWithPoints().
TestChangingCurveWithPoints()
void EngineTests.calculus.MutablePiecewiseInterpolatedCurveTests.TestChangingCurveWithPoints (IEnumerable< LiteralResultPoint > pointsEnumerable) inline
Definition at line 196 of file MutablePiecewiseInterpolatedCurveTests.cs.
        {
            var origPoints = new List<LiteralResultPoint>(pointsEnumerable);
            var mutablePoints = new List<MutableLiteralResultPoint>(origPoints.Count);
            var mutableCurve = LiteralCurve.NewMutable();
            foreach (var p in origPoints)
            {
                var mutablePoint = mutableCurve.NewPoint();
                mutablePoint.CompletePoint = p;
                mutablePoints.Add(mutablePoint);
            }
            ICurve<double> firstCurve = mutableCurve.CurrentCurve();
            foreach (var p in origPoints)
            {
                p.AssertOnCurve(firstCurve);
                p.AssertOnCurve(mutableCurve);
            }
            var replacementPoints = new List<LiteralResultPoint>(mutablePoints.Zip(RandomPoints(mutablePoints.Count),
                (mutablePoint, newValue) => mutablePoint.CompletePoint = newValue));
            // The new curve, and the current state of the mutable curve, should represent the new points.
            foreach (var p in replacementPoints)
            {
                p.AssertOnCurve(mutableCurve);
            }
            ICurve<double> secondCurve = mutableCurve.CurrentCurve();
            foreach (var p in replacementPoints)
            {
                p.AssertOnCurve(secondCurve);
            }
            // But the original curve should be unchanged.
            foreach (var p in origPoints)
            {
                p.AssertOnCurve(firstCurve);
            }
        }
TestUnchangingCurveWithPoints()
void EngineTests.calculus.MutablePiecewiseInterpolatedCurveTests.TestUnchangingCurveWithPoints (IEnumerable< LiteralResultPoint > pointsEnumerable) inline
Definition at line 172 of file MutablePiecewiseInterpolatedCurveTests.cs.
        {
            var points = new List<LiteralResultPoint>(pointsEnumerable);
            var mutableCurve = LiteralCurve.NewMutable();
            foreach (var p in points)
            {
                var mutablePoint = mutableCurve.NewPoint();
                mutablePoint.CompletePoint = p;
            }
            foreach (var p in points)
            {
                p.AssertOnCurve(mutableCurve);
            }
            ICurve<double> fixedCurve = mutableCurve.CurrentCurve();
            foreach (var p in points)
            {
                p.AssertOnCurve(fixedCurve);
            }
        }
Member Data Documentation
Rand
readonly Random EngineTests.calculus.MutablePiecewiseInterpolatedCurveTests.Rand = new Random() static private
Definition at line 158 of file MutablePiecewiseInterpolatedCurveTests.cs.
Referenced by EngineTests.calculus.MutablePiecewiseInterpolatedCurveTests.RandomPoint().
The documentation for this class was generated from the following file:
EngineTests/calculus/MutablePiecewiseInterpolatedCurveTests.cs