Anatomy3D: FreedomOfFormFoundation.AnatomyEngine.Calculus.ContinuousMap< TIn, TOut > Class Template Reference
FreedomOfFormFoundation.AnatomyEngine.Calculus.ContinuousMap< TIn, TOut > Class Template Reference abstract
Public Member Functions
abstract TOut GetValueAt (TIn t)
Static Public Member Functions
static implicit operator ContinuousMap< TIn, TOut > (TOut m)
static implicit operator ContinuousMap< TIn, TOut > (Func< TIn, TOut > f)
Private Member Functions
static implicit TOut (m)
Detailed Description
A ContinuousMap is an abstract class that defines some function that outputs a value of type TOut for each input of type TIn. Mathematically, this means it defines a mapping from one space to another. For example, a ContinuousMap<Real, Real> defines a function that takes a Real value and outputs a Real value, such as a polynomial function. ContinuousMap<Vector2, Real> takes a Vector2 as input and gives a Real as output, which could for instance be used as a height map.
Definition at line 28 of file ContinuousMap.cs.
Member Function Documentation
GetValueAt()
abstract TOut FreedomOfFormFoundation.AnatomyEngine.Calculus.ContinuousMap< TIn, TOut >.GetValueAt (TIn t) pure virtual
Implemented in FreedomOfFormFoundation.AnatomyEngine.Calculus.FunctionBackedContinuousMap< TIn, TOut >, FreedomOfFormFoundation.AnatomyEngine.Calculus.ConstantFunction< TIn, TOut >, and FreedomOfFormFoundation.AnatomyEngine.Calculus.ComposedMap< TIn, TIntermediate, TOut >.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.GenerateVertexList(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Hemisphere.GenerateVertexList(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.GetNormalAt(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.GetPositionAt(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Hemisphere.GetPositionAt(), FreedomOfFormFoundation.AnatomyEngine.Calculus.MoldCastMap.GetValueAt(), FreedomOfFormFoundation.AnatomyEngine.Calculus.ShiftedMap2D< TOut >.GetValueAt(), FreedomOfFormFoundation.AnatomyEngine.Geometry.SymmetricCylinder.RayIntersect(), EngineTests.FunctionBackedContinuousMapTests.TestCasts(), EngineTests.FunctionBackedContinuousMapTests.TestCompose(), and EngineTests.FunctionBackedContinuousMapTests.TestThen().
operator ContinuousMap< TIn, TOut >() [1/2]
static implicit FreedomOfFormFoundation.AnatomyEngine.Calculus.ContinuousMap< TIn, TOut >.operator ContinuousMap< TIn, TOut > (Func< TIn, TOut > f) inline static
Definition at line 34 of file ContinuousMap.cs.
         {
             return new FunctionBackedContinuousMap<TIn, TOut>(f);
         }
operator ContinuousMap< TIn, TOut >() [2/2]
static implicit FreedomOfFormFoundation.AnatomyEngine.Calculus.ContinuousMap< TIn, TOut >.operator ContinuousMap< TIn, TOut > (TOut m) static
TOut()
static implicit FreedomOfFormFoundation.AnatomyEngine.Calculus.ContinuousMap< TIn, TOut >.TOut (m) private
The documentation for this class was generated from the following file:
engine/calculus/ContinuousMap.cs