Anatomy3D: FreedomOfFormFoundation.AnatomyEngine.Real Struct Reference
FreedomOfFormFoundation.AnatomyEngine.Real Struct Reference
Struct Real wraps a floating-point representation, which can be changed at compile time to reveal numerical instability problems (by using float) or to minimize them (by using double). It also offers a window to add debugging hooks for math during development, watch for numerical instability, etc.
Public Member Functions
Real (double v)
Construct a Real with the value provided.
Real (float v)
Construct a Real with the value provided.
Real (decimal v)
Construct a Real with the value provided.
Real (sbyte v)
Construct a Real with the sbyte value provided.
Real (byte v)
Construct a Real with the byte value provided.
Real (short v)
Construct a Real with the short value provided.
Real (ushort v)
Construct a Real with the ushort value provided.
Real (int v)
Construct a Real with the int value provided.
Real (uint v)
Construct a Real with the uint value provided.
Real (long v)
Construct a Real with the long value provided.
Real (ulong v)
Construct a Real with the ulong value provided.
Real (Real r)
Construct a Real that is a copy of another Real.
string ToString (string format, IFormatProvider formatProvider)
int CompareTo (Real o)
bool Equals (Real o)
override bool Equals (object o)
override int GetHashCode ()
Calculate a hash code for this value.
bool IsAbsolutelyNear (Real o, Real slop)
Compares this Real value for being near another one, plus or minus a certain error range. NaN is not near anything (including NaN) and infinities are only near the same infinity.
bool IsRelativelyNear (Real o, Real slop)
Compares this Real value for being near another one, with a proportional difference no greater than a certain limit. NaN is not near anything (including NaN), infinities are only near the same infinity, and zero is only near zero (negative and positive zero are indistinct). Values of different signs are not relatively near each other. Proportion is relative to the smaller value.
bool IsNear (Real o, Real slop)
Returns whether this is near the other value, within either an absolute or relative range. NaN values are never near anything. Infinite values are only near themselves. Otherwise, values are near each other if the absolute value of the difference between them is less than the slop value, or if the proportional difference between them is less than the slop value (calculated relative to the smaller value).
Static Public Member Functions
static implicit operator Real (double d)
static implicit operator Real (float f)
static implicit operator Real (decimal m)
static implicit operator Real (sbyte x)
static implicit operator Real (byte x)
static implicit operator Real (short x)
static implicit operator Real (ushort x)
static implicit operator Real (int x)
static implicit operator Real (uint x)
static implicit operator Real (long x)
static implicit operator Real (ulong x)
static operator double (Real real)
static operator float (Real real)
static operator decimal (Real real)
static operator sbyte (Real real)
static operator byte (Real real)
static operator short (Real real)
static operator ushort (Real real)
static operator int (Real real)
static operator uint (Real real)
static operator long (Real real)
static operator ulong (Real real)
static operator Complex (Real real)
Convert a Real to a Complex with zero imaginary part.
static bool operator true (Real r)
static bool operator false (Real r)
static Real operator! (Real r)
Implements logical inversion on a floating-point value, extending the semantics of C# to do so. NaN values remain NaN. Otherwise, positive and negative zero both become 1.0, and all nonzero non-NaN values become 0.0.
static Real operator+ (Real r)
static Real operator- (Real r)
static Real operator++ (Real r)
static Real operator-- (Real r)
static Real operator+ (Real left, Real right)
static Real operator- (Real left, Real right)
static Real operator* (Real left, Real right)
static Real operator/ (Real left, Real right)
static Real operator% (Real left, Real right)
static bool operator< (Real left, Real right)
static bool operator> (Real left, Real right)
static bool operator== (Real left, Real right)
static bool operator!= (Real left, Real right)
static bool operator<= (Real left, Real right)
static bool operator>= (Real left, Real right)
Static Public Attributes
static readonly Real NaN = new Real(double.NaN)
static readonly Real NegativeInfinity = new Real(double.NegativeInfinity)
static readonly Real PositiveInfinity = new Real(double.PositiveInfinity)
Properties
bool IsNaN [get]
bool IsInfinity [get]
bool IsPositiveInfinity [get]
bool IsNegativeInfinity [get]
bool IsFinite [get]
Private Member Functions
bool? NearSpecialCases (Real o)
Special cases for nearness checks: handles infinities and NaN. Actually an equality check in these cases, treating NaN as unequal to NaN.
Private Attributes
readonly double _v
Detailed Description
Struct Real wraps a floating-point representation, which can be changed at compile time to reveal numerical instability problems (by using float) or to minimize them (by using double). It also offers a window to add debugging hooks for math during development, watch for numerical instability, etc.
Definition at line 52 of file Real.cs.
Constructor & Destructor Documentation
Real() [1/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (double v) inline
Construct a Real with the value provided.
Parameters
v Value this Real should take.
Definition at line 69 of file Real.cs.
         {
 #if REALTYPE_DOUBLE
             _v = v;
 #elif REALTYPE_FLOAT
             _v = (float) v;
 #elif REALTYPE_DECIMAL
             _v = (decimal) v;
 #else
             #error Real doesn't know how to cast from double
 #endif
         }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Real.operator!().
Real() [2/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (float v) inline
Construct a Real with the value provided.
Parameters
v Value this Real should take.
Definition at line 86 of file Real.cs.
         {
 #if REALTYPE_DOUBLE
             _v = (double) v;
 #elif REALTYPE_FLOAT
             _v = v;
 #elif REALTYPE_DECIMAL
             _v = (decimal) v;
 #else
             #error Real doesn't know how to cast from float
 #endif
         }
Real() [3/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (decimal v) inline
Construct a Real with the value provided.
Parameters
v Value this Real should take.
Definition at line 103 of file Real.cs.
         {
 #if REALTYPE_DOUBLE
             _v = (double) v;
 #elif REALTYPE_FLOAT
             _v = (float) v;
 #elif REALTYPE_DECIMAL
             _v = v;
 #else
             #error Real doesn't know how to cast from decimal
 #endif
         }
Real() [4/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (sbyte v) inline
Construct a Real with the sbyte value provided.
Parameters
v Value this Real should take.
Definition at line 120 of file Real.cs.
         {
 #if REALTYPE_DOUBLE
             _v = (double) v;
 #elif REALTYPE_FLOAT
             _v = (float) v;
 #elif REALTYPE_DECIMAL
             _v = (decimal) v;
 #else
             #error Real doesn't know how to cast from sbyte
 #endif
         }
Real() [5/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (byte v) inline
Construct a Real with the byte value provided.
Parameters
v Value this Real should take.
Definition at line 137 of file Real.cs.
         {
 #if REALTYPE_DOUBLE
             _v = (double) v;
 #elif REALTYPE_FLOAT
             _v = (float) v;
 #elif REALTYPE_DECIMAL
             _v = (decimal) v;
 #else
              #error Real doesn't know how to cast from byte
 #endif
         }
Real() [6/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (short v) inline
Construct a Real with the short value provided.
Parameters
v Value this Real should take.
Definition at line 154 of file Real.cs.
         {
 #if REALTYPE_DOUBLE
             _v = (double) v;
 #elif REALTYPE_FLOAT
             _v = (float) v;
 #elif REALTYPE_DECIMAL
             _v = (decimal) v;
 #else
              #error Real doesn't know how to cast from short
 #endif
         }
Real() [7/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (ushort v) inline
Construct a Real with the ushort value provided.
Parameters
v Value this Real should take.
Definition at line 171 of file Real.cs.
         {
 #if REALTYPE_DOUBLE
             _v = (double) v;
 #elif REALTYPE_FLOAT
             _v = (float) v;
 #elif REALTYPE_DECIMAL
             _v = (decimal) v;
 #else
              #error Real doesn't know how to cast from ushort
 #endif
         }
Real() [8/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (int v) inline
Construct a Real with the int value provided.
Parameters
v Value this Real should take.
Definition at line 188 of file Real.cs.
         {
 #if REALTYPE_DOUBLE
             _v = (double) v;
 #elif REALTYPE_FLOAT
             _v = (float) v;
 #elif REALTYPE_DECIMAL
             _v = (decimal) v;
 #else
              #error Real doesn't know how to cast from int
 #endif
         }
Real() [9/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (uint v) inline
Construct a Real with the uint value provided.
Parameters
v Value this Real should take.
Definition at line 205 of file Real.cs.
         {
 #if REALTYPE_DOUBLE
             _v = (double) v;
 #elif REALTYPE_FLOAT
             _v = (float) v;
 #elif REALTYPE_DECIMAL
             _v = (decimal) v;
 #else
              #error Real doesn't know how to cast from uint
 #endif
         }
Real() [10/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (long v) inline
Construct a Real with the long value provided.
Parameters
v Value this Real should take.
Definition at line 222 of file Real.cs.
         {
 #if REALTYPE_DOUBLE
             _v = (double) v;
 #elif REALTYPE_FLOAT
             _v = (float) v;
 #elif REALTYPE_DECIMAL
             _v = (decimal) v;
 #else
              #error Real doesn't know how to cast from long
 #endif
         }
Real() [11/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (ulong v) inline
Construct a Real with the ulong value provided.
Parameters
v Value this Real should take.
Definition at line 239 of file Real.cs.
         {
 #if REALTYPE_DOUBLE
             _v = (double) v;
 #elif REALTYPE_FLOAT
             _v = (float) v;
 #elif REALTYPE_DECIMAL
             _v = (decimal) v;
 #else
              #error Real doesn't know how to cast from ulong
 #endif
         }
Real() [12/12]
FreedomOfFormFoundation.AnatomyEngine.Real.Real (Real r) inline
Construct a Real that is a copy of another Real.
Parameters
r Value to copy.
Definition at line 256 of file Real.cs.
         {
             _v = r._v;
         }
Member Function Documentation
CompareTo()
int FreedomOfFormFoundation.AnatomyEngine.Real.CompareTo (Real o)
Equals() [1/2]
override bool FreedomOfFormFoundation.AnatomyEngine.Real.Equals (object o) inline
Definition at line 329 of file Real.cs.
         {
             switch (o)
             {
                 case null:
                     return false;
                 case Real real:
                     return this.Equals(real);
                 default:
                     return false;
             }
         }
Equals() [2/2]
bool FreedomOfFormFoundation.AnatomyEngine.Real.Equals (Real o) inline
Definition at line 324 of file Real.cs.
         {
             return _v.Equals(o._v);
         }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Real.Equals(), FreedomOfFormFoundation.AnatomyEngine.Real.NearSpecialCases(), and EngineTests.RealTests.TestEqualsFunction().
GetHashCode()
override int FreedomOfFormFoundation.AnatomyEngine.Real.GetHashCode () inline
Calculate a hash code for this value.
Rearranges and inverts the bits of the hash of the underlying type to make it hash differently.
Returns
An arbitrary 32-bit integer, equal between equal instances of this type with no particular guarantees otherwise, but with an attempt to be scattered. Allows this type to be used as a key in a hashed data structure (although, frankly, it would be a pretty weird key type).
Definition at line 352 of file Real.cs.
         {
             int h = _v.GetHashCode();
             return ~(h << 16 | h >> 16);
         }
IsAbsolutelyNear()
bool FreedomOfFormFoundation.AnatomyEngine.Real.IsAbsolutelyNear (Real o, Real slop) inline
Compares this Real value for being near another one, plus or minus a certain error range. NaN is not near anything (including NaN) and infinities are only near the same infinity.
Parameters
o Value to compare to.
slop Amount of error that can still be considered equal. Nonnegative.
Returns
Whether this is in the closed range of o ± slop.
Definition at line 466 of file Real.cs.
         {
             if (slop < 0.0)
             {
                 throw new ArgumentException("slop cannot be negative.","slop");
             }
             bool? sc = NearSpecialCases(o);
             if (sc != null)
             {
                 return sc.Value;
             }
             Real diff = this - o;
             if (diff < 0.0) diff = -diff;
             return diff <= slop;
         }
IsNear()
bool FreedomOfFormFoundation.AnatomyEngine.Real.IsNear (Real o, Real slop)
Returns whether this is near the other value, within either an absolute or relative range. NaN values are never near anything. Infinite values are only near themselves. Otherwise, values are near each other if the absolute value of the difference between them is less than the slop value, or if the proportional difference between them is less than the slop value (calculated relative to the smaller value).
Parameters
o Value to compare against.
slop Allowable amount of error, either absolute or proportional, for values to be considered near each other. Nonnegative.
Returns
IsRelativelyNear()
bool FreedomOfFormFoundation.AnatomyEngine.Real.IsRelativelyNear (Real o, Real slop) inline
Compares this Real value for being near another one, with a proportional difference no greater than a certain limit. NaN is not near anything (including NaN), infinities are only near the same infinity, and zero is only near zero (negative and positive zero are indistinct). Values of different signs are not relatively near each other. Proportion is relative to the smaller value.
Parameters
o Value to compare this to.
slop Proportional difference tolerated between values. Nonnegative.
Returns
Whether this is near o, within the given proportion.
Definition at line 492 of file Real.cs.
         {
             if (slop < 0.0)
             {
                 throw new ArgumentException("slop cannot be negative.", "slop");
             }
             bool? sc = NearSpecialCases(o);
             if (sc != null)
             {
                 return sc.Value;
             }
             if (o == 0.0)
             {
                 // Zero is not relatively near anything else.
                 return this == 0.0;
             }
             Real big, little;
             if (this < 0.0)
             {
                 if (o > 0.0) return false;
                 // Negative values; "big" and "little" refer to magnitude and the signs will cancel
                 // out during division, so reverse the obvious semantics for which goes where.
                 if (this > o)
                 {
                     big = o;
                     little = this;
                 }
                 else
                 {
                     big = this;
                     little = o;
                 }
             }
             else
             {
                 if (o < 0.0) return false;
                 if (this > o)
                 {
                     big = this;
                     little = o;
                 }
                 else
                 {
                     big = o;
                     little = this;
                 }
             }
             Real ratio = big / little;
             return (ratio - 1.0) <= slop;
         }
Referenced by EngineTests.calculus.QuadraticFunctionTests.Near().
NearSpecialCases()
bool? FreedomOfFormFoundation.AnatomyEngine.Real.NearSpecialCases (Real o) inline private
Special cases for nearness checks: handles infinities and NaN. Actually an equality check in these cases, treating NaN as unequal to NaN.
Parameters
o Number to compare this to.
Returns
null if no special case applies; otherwise, result of equality check.
Definition at line 435 of file Real.cs.
         {
             if (IsNaN || o.IsNaN)
             {
                 // NaN is not similar to anything else - even itself.
                 return false;
             }
             if (IsInfinity)
             {
                 // Infinities are only near the exactly identical infinity,
                 // regardless of the slop factor.
                 return Equals(o);
             }
             if (o.IsInfinity)
             {
                 // this isn't infinity or we would have gotten into the previous case.
                 return false;
             }
             return null;
         }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Real.IsAbsolutelyNear(), and FreedomOfFormFoundation.AnatomyEngine.Real.IsRelativelyNear().
operator byte()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator byte (Real real) explicit static
operator Complex()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator Complex (Real real) explicit static
Convert a Real to a Complex with zero imaginary part.
Parameters
real Real to convert.
Returns
Complex with real part equal to the provided Real (as double) and zero imaginary part.
operator decimal()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator decimal (Real real) explicit static
operator double()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator double (Real real) explicit static
operator false()
static bool FreedomOfFormFoundation.AnatomyEngine.Real.operator false (Real r) static
operator float()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator float (Real real) explicit static
operator int()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator int (Real real) explicit static
operator long()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator long (Real real) explicit static
operator Real() [1/11]
static implicit FreedomOfFormFoundation.AnatomyEngine.Real.operator Real (byte x) static
operator Real() [2/11]
static implicit FreedomOfFormFoundation.AnatomyEngine.Real.operator Real (decimal m) static
operator Real() [3/11]
static implicit FreedomOfFormFoundation.AnatomyEngine.Real.operator Real (double d) static
operator Real() [4/11]
static implicit FreedomOfFormFoundation.AnatomyEngine.Real.operator Real (float f) static
operator Real() [5/11]
static implicit FreedomOfFormFoundation.AnatomyEngine.Real.operator Real (int x) static
operator Real() [6/11]
static implicit FreedomOfFormFoundation.AnatomyEngine.Real.operator Real (long x) static
operator Real() [7/11]
static implicit FreedomOfFormFoundation.AnatomyEngine.Real.operator Real (sbyte x) static
operator Real() [8/11]
static implicit FreedomOfFormFoundation.AnatomyEngine.Real.operator Real (short x) static
operator Real() [9/11]
static implicit FreedomOfFormFoundation.AnatomyEngine.Real.operator Real (uint x) static
operator Real() [10/11]
static implicit FreedomOfFormFoundation.AnatomyEngine.Real.operator Real (ulong x) static
operator Real() [11/11]
static implicit FreedomOfFormFoundation.AnatomyEngine.Real.operator Real (ushort x) static
operator sbyte()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator sbyte (Real real) explicit static
operator short()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator short (Real real) explicit static
operator true()
static bool FreedomOfFormFoundation.AnatomyEngine.Real.operator true (Real r) inline static
Definition at line 562 of file Real.cs.
         {
 #if (REALTYPE_DOUBLE || REALTYPE_FLOAT)
             if (r.IsNaN) return false;
 #endif
             return r._v != 0;
         }
operator uint()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator uint (Real real) explicit static
operator ulong()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator ulong (Real real) explicit static
operator ushort()
static FreedomOfFormFoundation.AnatomyEngine.Real.operator ushort (Real real) explicit static
operator!()
static Real FreedomOfFormFoundation.AnatomyEngine.Real.operator! (Real r) inline static
Implements logical inversion on a floating-point value, extending the semantics of C# to do so. NaN values remain NaN. Otherwise, positive and negative zero both become 1.0, and all nonzero non-NaN values become 0.0.
Parameters
r Value to invert.
Returns
Logical inversion of r. NaN remains NaN.
Definition at line 579 of file Real.cs.
         {
 #if !REALTYPE_DECIMAL
             if (r.IsNaN)
             {
                 return Real.NaN;
             }
 #endif
             if (r._v == 0)
             {
                 return new Real(1.0);
             }
             return new Real(0.0);
         }
operator!=()
static bool FreedomOfFormFoundation.AnatomyEngine.Real.operator!= (Real left, Real right) static
operator%()
static Real FreedomOfFormFoundation.AnatomyEngine.Real.operator% (Real left, Real right) static
operator*()
static Real FreedomOfFormFoundation.AnatomyEngine.Real.operator* (Real left, Real right) static
operator+() [1/2]
static Real FreedomOfFormFoundation.AnatomyEngine.Real.operator+ (Real left, Real right) static
operator+() [2/2]
static Real FreedomOfFormFoundation.AnatomyEngine.Real.operator+ (Real r) static
operator++()
static Real FreedomOfFormFoundation.AnatomyEngine.Real.operator++ (Real r) static
operator-() [1/2]
static Real FreedomOfFormFoundation.AnatomyEngine.Real.operator- (Real left, Real right) static
operator-() [2/2]
static Real FreedomOfFormFoundation.AnatomyEngine.Real.operator- (Real r) static
operator--()
static Real FreedomOfFormFoundation.AnatomyEngine.Real.operator-- (Real r) static
operator/()
static Real FreedomOfFormFoundation.AnatomyEngine.Real.operator/ (Real left, Real right) static
operator<()
static bool FreedomOfFormFoundation.AnatomyEngine.Real.operator< (Real left, Real right) static
operator<=()
static bool FreedomOfFormFoundation.AnatomyEngine.Real.operator<= (Real left, Real right) static
operator==()
static bool FreedomOfFormFoundation.AnatomyEngine.Real.operator== (Real left, Real right) static
operator>()
static bool FreedomOfFormFoundation.AnatomyEngine.Real.operator> (Real left, Real right) static
operator>=()
static bool FreedomOfFormFoundation.AnatomyEngine.Real.operator>= (Real left, Real right) static
ToString()
string FreedomOfFormFoundation.AnatomyEngine.Real.ToString (string format, IFormatProvider formatProvider) inline
Definition at line 317 of file Real.cs.
         {
             return _v.ToString(format, formatProvider);
         }
Member Data Documentation
_v
readonly double FreedomOfFormFoundation.AnatomyEngine.Real._v private
Definition at line 55 of file Real.cs.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Real.Equals(), FreedomOfFormFoundation.AnatomyEngine.Real.GetHashCode(), FreedomOfFormFoundation.AnatomyEngine.Real.operator!(), FreedomOfFormFoundation.AnatomyEngine.Real.Real(), and FreedomOfFormFoundation.AnatomyEngine.Real.ToString().
NaN
readonly Real FreedomOfFormFoundation.AnatomyEngine.Real.NaN = new Real(double.NaN) static
Definition at line 265 of file Real.cs.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Real.operator!(), EngineTests.RealTests.TestAddition(), EngineTests.RealTests.TestEqualsFunction(), and EngineTests.RealTests.TestEqualsOperator().
NegativeInfinity
readonly Real FreedomOfFormFoundation.AnatomyEngine.Real.NegativeInfinity = new Real(double.NegativeInfinity) static
Definition at line 266 of file Real.cs.
Referenced by EngineTests.RealTests.TestAddition(), EngineTests.RealTests.TestEqualsFunction(), and EngineTests.RealTests.TestEqualsOperator().
PositiveInfinity
readonly Real FreedomOfFormFoundation.AnatomyEngine.Real.PositiveInfinity = new Real(double.PositiveInfinity) static
Definition at line 267 of file Real.cs.
Referenced by EngineTests.RealTests.TestAddition(), EngineTests.RealTests.TestEqualsFunction(), and EngineTests.RealTests.TestEqualsOperator().
Property Documentation
IsFinite
bool FreedomOfFormFoundation.AnatomyEngine.Real.IsFinite get
Definition at line 424 of file Real.cs.
IsInfinity
bool FreedomOfFormFoundation.AnatomyEngine.Real.IsInfinity get
Definition at line 376 of file Real.cs.
         {
             get
             {
 #if REALTYPE_DOUBLE
                 return double.IsInfinity(_v);
 #elif REALTYPE_FLOAT
                 return float.IsInfinity(_v);
 #elif REALTYPE_DECIMAL
                 return false;
 #else
                 #error Real doesn't know how to calculate IsInfinity for its current type.
 #endif
             }
         }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Real.NearSpecialCases().
IsNaN
bool FreedomOfFormFoundation.AnatomyEngine.Real.IsNaN get
Definition at line 360 of file Real.cs.
         {
             get
             {
 #if REALTYPE_DOUBLE
                 return double.IsNaN(_v);
 #elif REALTYPE_FLOAT
                 return float.IsNaN(_v);
 #elif REALTYPE_DECIMAL
                 return false;
 #else
                 #error Real doesn't know how to calculate IsNaN for its current type.
 #endif
             }
         }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Real.NearSpecialCases(), and FreedomOfFormFoundation.AnatomyEngine.Real.operator!().
IsNegativeInfinity
bool FreedomOfFormFoundation.AnatomyEngine.Real.IsNegativeInfinity get
Definition at line 408 of file Real.cs.
         {
             get
             {
 #if REALTYPE_DOUBLE
                 return double.IsNegativeInfinity(_v);
 #elif REALTYPE_FLOAT
                 return float.IsNegativeInfinity(_v);
 #elif REALTYPE_DECIMAL
                 return false;
 #else
 #error Real doesn't know how to calculate IsNegativeInfinity for its current type.
 #endif
             }
         }
IsPositiveInfinity
bool FreedomOfFormFoundation.AnatomyEngine.Real.IsPositiveInfinity get
Definition at line 392 of file Real.cs.
         {
             get
             {
 #if REALTYPE_DOUBLE
                 return double.IsPositiveInfinity(_v);
 #elif REALTYPE_FLOAT
                 return float.IsPositiveInfinity(_v);
 #elif REALTYPE_DECIMAL
                 return false;
 #else
 #error Real doesn't know how to calculate IsPositiveInfinity for its current type.
 #endif
             }
         }
The documentation for this struct was generated from the following file:
engine/Real.cs