Anatomy3D: FreedomOfFormFoundation.AnatomyEngine.DebugUtil Class Reference
FreedomOfFormFoundation.AnatomyEngine.DebugUtil Class Reference
DebugUtil contains assorted void methods that are not compiled into release builds. They contain various assertions and checks for potential bugs that should be detected as close as possible to where they arise, but the performance impact of these checks would be inappropriate in a release build.
Static Public Member Functions
static void AssertFinite (double x, string varName)
AssertFinite crashes the program (in debug mode) if x is infinite or NaN. It does not object to negative zero.
static void AssertAllFinite (IEnumerable< double > items, string varName)
AssertAllFinite crashes the program (in debug mode) if any item in items is infinite or NaN. It does not object to negative zero.
static void AssertAllFinite (SortedPointsList< double > items, string varName)
AssertAllFinite crashes the program (in debug mode) if any element of any point in the SortedPointsList is infinite or NaN. It does not object to negative zero.
Detailed Description
DebugUtil contains assorted void methods that are not compiled into release builds. They contain various assertions and checks for potential bugs that should be detected as close as possible to where they arise, but the performance impact of these checks would be inappropriate in a release build.
Definition at line 30 of file DebugUtil.cs.
Member Function Documentation
AssertAllFinite() [1/2]
static void FreedomOfFormFoundation.AnatomyEngine.DebugUtil.AssertAllFinite (IEnumerable< double > items, string varName) inline static
AssertAllFinite crashes the program (in debug mode) if any item in items is infinite or NaN. It does not object to negative zero.
Parameters
items Collection of items to range check.
varName Name of variable being checked (use nameof); included in error message.
Definition at line 55 of file DebugUtil.cs.
        {
            uint idx = 0;
            foreach (double item in items)
            {
                AssertFinite(item, $"{varName}[{idx}]");
                idx++;
            }
        }
Referenced by FreedomOfFormFoundation.AnatomyEngine.DebugUtil.AssertAllFinite(), FreedomOfFormFoundation.AnatomyEngine.Calculus.CubicSpline1D.CubicSpline1D(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.GetNormalAt(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.GetPositionAt(), FreedomOfFormFoundation.AnatomyEngine.Calculus.MoldCastMap.GetValueAt(), FreedomOfFormFoundation.AnatomyEngine.Calculus.ShiftedMap2D< TOut >.GetValueAt(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Hemisphere.Hemisphere(), FreedomOfFormFoundation.AnatomyEngine.Calculus.QuarticFunction.QuarticFunction(), FreedomOfFormFoundation.AnatomyEngine.Geometry.SymmetricCylinder.RayIntersect(), FreedomOfFormFoundation.AnatomyEngine.Calculus.ShiftedMap2D< TOut >.ShiftedMap2D(), FreedomOfFormFoundation.AnatomyEngine.Calculus.QuarticFunction.Solve(), and FreedomOfFormFoundation.AnatomyEngine.Calculus.CubicSpline1D.ThomasAlgorithm().
AssertAllFinite() [2/2]
static void FreedomOfFormFoundation.AnatomyEngine.DebugUtil.AssertAllFinite (SortedPointsList< double > items, string varName) inline static
AssertAllFinite crashes the program (in debug mode) if any element of any point in the SortedPointsList is infinite or NaN. It does not object to negative zero.
Parameters
items Collection of items to range check.
varName Name of variable being checked (use nameof); included in error message.
Definition at line 72 of file DebugUtil.cs.
        {
            AssertAllFinite(items.Key, $"{varName}.Key");
            AssertAllFinite(items.Value, $"{varName}.Value");
        }
AssertFinite()
static void FreedomOfFormFoundation.AnatomyEngine.DebugUtil.AssertFinite (double x, string varName) inline static
AssertFinite crashes the program (in debug mode) if x is infinite or NaN. It does not object to negative zero.
Parameters
x Value to range check.
varName Name of variable being checked (use nameof); included in error message.
Definition at line 39 of file DebugUtil.cs.
        {
            Debug.Assert(
                !double.IsInfinity(x) && !double.IsNaN(x),
                "Transfinite double error",
                "Variable {0}, expected to be finite, had illegal value {1}.",
                varName, x);
        }
Referenced by FreedomOfFormFoundation.AnatomyEngine.DebugUtil.AssertAllFinite(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.Cylinder(), FreedomOfFormFoundation.AnatomyEngine.Calculus.CubicFunction.GetNthDerivativeAt(), FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.GetNthDerivativeAt(), FreedomOfFormFoundation.AnatomyEngine.Calculus.QuarticFunction.GetNthDerivativeAt(), FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.QuadraticFunction(), FreedomOfFormFoundation.AnatomyEngine.Geometry.SymmetricCylinder.RayIntersect(), FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.Solve(), FreedomOfFormFoundation.AnatomyEngine.Calculus.CubicFunction.Solve(), and FreedomOfFormFoundation.AnatomyEngine.Calculus.QuarticFunction.Solve().
The documentation for this class was generated from the following file:
engine/utilities/DebugUtil.cs