Anatomy3D: FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve Class Reference
FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve Class Reference abstract
A Curve defines any finite one-dimensional path in 3D space, with a start and end point.
Public Member Functions
abstract dvec3 GetPositionAt (double t)
Returns the position in 3D space of the curve based on the parametric variable t .
abstract dvec3 GetTangentAt (double t)
Returns the tangent vector of the curve based on the parametric variable t .
abstract dvec3 GetNormalAt (double t)
Returns the normal vector of the curve based on the parametric variable t .
virtual dvec3 GetBinormalAt (double t)
Returns the binormal vector of the curve based on the parametric variable t .
virtual dvec3 GetStartPosition ()
Returns the position in 3D space of the start point of the curve. Should return the same value as getPositionAt(0.0).
virtual dvec3 GetEndPosition ()
Returns the position in 3D space of the end point of the curve. Should return the same value as getPositionAt(1.0).
override dvec3 GetValueAt (double t)
Public Member Functions inherited from FreedomOfFormFoundation.AnatomyEngine.Calculus.ContinuousMap< double, dvec3 >
abstract TOut GetValueAt (TIn t)
Additional Inherited Members
Static Public Member Functions inherited from FreedomOfFormFoundation.AnatomyEngine.Calculus.ContinuousMap< double, dvec3 >
static implicit operator ContinuousMap< TIn, TOut > (TOut m)
static implicit operator ContinuousMap< TIn, TOut > (Func< TIn, TOut > f)
Detailed Description
A Curve defines any finite one-dimensional path in 3D space, with a start and end point.
Definition at line 26 of file Curve.cs.
Member Function Documentation
GetBinormalAt()
virtual dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetBinormalAt (double t) inline virtual
Returns the binormal vector of the curve based on the parametric variable t .
Parameters
t The parameter along the length of the curve. t must be in the range \([ 0, 1 ]\).
Definition at line 54 of file Curve.cs.
        {
            return dvec3.Cross(GetTangentAt(t), GetNormalAt(t));
        }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.SymmetricCylinder.RayIntersect().
GetEndPosition()
virtual dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetEndPosition () inline virtual
Returns the position in 3D space of the end point of the curve. Should return the same value as getPositionAt(1.0).
Reimplemented in FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment, and FreedomOfFormFoundation.AnatomyEngine.Geometry.SpatialCubicSpline.
Definition at line 72 of file Curve.cs.
        {
            return GetPositionAt(1.0);
        }
GetNormalAt()
abstract dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetNormalAt (double t) pure virtual
Returns the normal vector of the curve based on the parametric variable t .
Parameters
t The parameter along the length of the curve. t must be in the range \([ 0, 1 ]\).
Implemented in FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment, and FreedomOfFormFoundation.AnatomyEngine.Geometry.SpatialCubicSpline.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.GenerateVertexList(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetBinormalAt(), and FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.GetNormalAt().
GetPositionAt()
abstract dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetPositionAt (double t) pure virtual
Returns the position in 3D space of the curve based on the parametric variable t .
Parameters
t The parameter along the length of the curve. t must be in the range \([ 0, 1 ]\).
Implemented in FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment, and FreedomOfFormFoundation.AnatomyEngine.Geometry.SpatialCubicSpline.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.GenerateVertexList(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetEndPosition(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.GetPositionAt(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetStartPosition(), and FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetValueAt().
GetStartPosition()
virtual dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetStartPosition () inline virtual
Returns the position in 3D space of the start point of the curve. Should return the same value as getPositionAt(0.0).
Reimplemented in FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment, and FreedomOfFormFoundation.AnatomyEngine.Geometry.SpatialCubicSpline.
Definition at line 63 of file Curve.cs.
        {
            return GetPositionAt(0.0);
        }
GetTangentAt()
abstract dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetTangentAt (double t) pure virtual
Returns the tangent vector of the curve based on the parametric variable t .
Parameters
t The parameter along the length of the curve. t must be in the range \([ 0, 1 ]\).
Implemented in FreedomOfFormFoundation.AnatomyEngine.Geometry.LineSegment, and FreedomOfFormFoundation.AnatomyEngine.Geometry.SpatialCubicSpline.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.GenerateVertexList(), FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetBinormalAt(), and FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.GetNormalAt().
GetValueAt()
override dvec3 FreedomOfFormFoundation.AnatomyEngine.Geometry.Curve.GetValueAt (double t) inline
Definition at line 78 of file Curve.cs.
        {
            return GetPositionAt(t);
        }
The documentation for this class was generated from the following file:
engine/geometry/Curve.cs