Anatomy3D: FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction Class Reference
FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction Class Reference
Class QuadraticFunction describes a quadratic function defined by \(q(x) = a_0 + a_1 x + a_2 x^2\).
Public Member Functions
QuadraticFunction (double a0, double a1, double a2)
A quadratic function defined by \(q(x) = a_0 + a_1 x + a_2 x^2\).
override double GetNthDerivativeAt (double x, uint derivative)
override double GetValueAt (double x)
IEnumerable< double > Roots ()
Solves the equation \(a_0 + a_1 x + a_2 x^2 = 0\), returning all real values of \(x\) for which the equation is true using the 'abc-formula' using the parameters in this instance of QuadraticFunction.
Public Member Functions inherited from FreedomOfFormFoundation.AnatomyEngine.Calculus.DerivableFunction< double, double >
abstract TOut GetNthDerivativeAt (TIn x, uint derivative)
Calculate the given derivative of this curve at the provided location. There is no standard for representing undefined derivatives; document your decisions.
TOut GetDerivativeAt (TIn x)
Calculate the first derivative of this derivable function at the provided location. ICurve<TOut>.GetDerivativeAt
Static Public Member Functions
static IEnumerable< double > Solve (double a0, double a1, double a2)
Solves a general equation \(a_0 + a_1 x + a_2 x^2 = 0\), returning all real values of \(x\) for which the equation is true using the 'abc-formula'.
Private Attributes
readonly double _a0
readonly double _a1
readonly double _a2
Detailed Description
Class QuadraticFunction describes a quadratic function defined by \(q(x) = a_0 + a_1 x + a_2 x^2\).
Definition at line 25 of file QuadraticFunction.cs.
Constructor & Destructor Documentation
QuadraticFunction()
FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.QuadraticFunction (double a0, double a1, double a2) inline
A quadratic function defined by \(q(x) = a_0 + a_1 x + a_2 x^2\).
Definition at line 34 of file QuadraticFunction.cs.
        {
            DebugUtil.AssertFinite(a0, nameof(a0));
            DebugUtil.AssertFinite(a1, nameof(a1));
            DebugUtil.AssertFinite(a2, nameof(a2));
            _a0 = a0;
            _a1 = a1;
            _a2 = a2;
        }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.Solve().
Member Function Documentation
GetNthDerivativeAt()
override double FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.GetNthDerivativeAt (double x, uint derivative) inline
Definition at line 45 of file QuadraticFunction.cs.
        {
            DebugUtil.AssertFinite(x, nameof(x));
            // Return a different function depending on the derivative level:
            switch (derivative)
            {
                case 0: return _a0 + _a1*x + _a2*x*x;
                case 1: return _a1 + 2.0f*_a2*x;
                case 2: return 2.0f*_a2;
                default: return 0.0f;
            }
        }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.GetValueAt(), EngineTests.calculus.QuadraticFunctionTests.TestDerivativesAt(), and EngineTests.calculus.QuadraticFunctionTests.TestValueCalculation().
GetValueAt()
override double FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.GetValueAt (double x) inline
Definition at line 59 of file QuadraticFunction.cs.
        {
            return GetNthDerivativeAt(x, 0);
        }
Referenced by EngineTests.calculus.QuadraticFunctionTests.TestValueCalculation().
Roots()
IEnumerable< double > FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.Roots () inline
Solves the equation \(a_0 + a_1 x + a_2 x^2 = 0\), returning all real values of \(x\) for which the equation is true using the 'abc-formula' using the parameters in this instance of QuadraticFunction.
Definition at line 69 of file QuadraticFunction.cs.
        {
            return Solve(_a0, _a1, _a2);
        }
Solve()
static IEnumerable< double > FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.Solve (double a0, double a1, double a2) inline static
Solves a general equation \(a_0 + a_1 x + a_2 x^2 = 0\), returning all real values of \(x\) for which the equation is true using the 'abc-formula'.
Definition at line 78 of file QuadraticFunction.cs.
        {
            DebugUtil.AssertFinite(a0, nameof(a0));
            DebugUtil.AssertFinite(a1, nameof(a1));
            DebugUtil.AssertFinite(a2, nameof(a2));
            if(Math.Abs(a2) <= 0.005)
            {
                if(Math.Abs(a1) <= 0.005)
                {
                    // There are no roots found:
                    yield break;
                } else {
                    // There is a single root, found from solving the linear equation with a1=0. We find a point close
                    // to the root using the linear approximation, after which we approach the true solution using the
                    // Newton-Raphson method:
                    QuadraticFunction f = new QuadraticFunction(a0, a1, a2);
                    yield return f.NewtonRaphson(-a0 / a1);
                }
                yield break;
            }
            double x1 = 0.5*(-a1 + Math.Sqrt(a1*a1 - 4.0*a0*a2))/a2;
            double x2 = 0.5*(-a1 - Math.Sqrt(a1*a1 - 4.0*a0*a2))/a2;
            if(Double.IsNaN(x1) == false)
            {
                yield return x1;
            }
            if(Double.IsNaN(x2) == false)
            {
                yield return x2;
            }
        }
Referenced by FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.Roots(), FreedomOfFormFoundation.AnatomyEngine.Calculus.CubicFunction.Solve(), and EngineTests.calculus.QuadraticFunctionTests.TestSolve().
Member Data Documentation
_a0
readonly double FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction._a0 private
Definition at line 27 of file QuadraticFunction.cs.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.GetNthDerivativeAt(), FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.QuadraticFunction(), and FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.Roots().
_a1
readonly double FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction._a1 private
Definition at line 28 of file QuadraticFunction.cs.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.GetNthDerivativeAt(), FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.QuadraticFunction(), and FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.Roots().
_a2
readonly double FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction._a2 private
Definition at line 29 of file QuadraticFunction.cs.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.GetNthDerivativeAt(), FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.QuadraticFunction(), and FreedomOfFormFoundation.AnatomyEngine.Calculus.QuadraticFunction.Roots().
The documentation for this class was generated from the following file:
engine/calculus/QuadraticFunction.cs