Anatomy3D: FreedomOfFormFoundation.AnatomyEngine.Geometry.Surface Class Reference
FreedomOfFormFoundation.AnatomyEngine.Geometry.Surface Class Reference abstract
Public Member Functions
abstract Vector3 GetNormalAt (Vector2 uv)
Returns the surface normal at the uv coordinate given.
abstract Vector3 GetPositionAt (Vector2 uv)
Returns the surface position at the uv coordinate given.
abstract List< Vertex > GenerateVertexList (int resolutionU, int resolutionV)
Generates the vertex positions of this uv-parametrized surface. The returned list will contain approximately resolutionU times resolutionV vertices in total. The meaning of the coordinates u and v depends on the specific type of surface.
abstract List< int > GenerateIndexList (int resolutionU, int resolutionV, int indexOffset=0)
Generates the indices pointing to vertices of this uv-parametrized surface. The returned list can contain any number of indices, since there will be a variable number of triangles depending on the surface type.
virtual UVMesh GenerateMesh (int resolutionU, int resolutionV, int indexOffset=0)
Generates the vertex positions and indices of this uv-parametrized surface. The returned list will contain approximately resolutionU times resolutionV vertices in total. The meaning of the coordinates u and v depends on the specific type of surface.
Detailed Description
Definition at line 7 of file Surface.cs.
Member Function Documentation
GenerateIndexList()
abstract List<int> FreedomOfFormFoundation.AnatomyEngine.Geometry.Surface.GenerateIndexList (int resolutionU, int resolutionV, int indexOffset = 0) pure virtual
Generates the indices pointing to vertices of this uv-parametrized surface. The returned list can contain any number of indices, since there will be a variable number of triangles depending on the surface type.
Implemented in FreedomOfFormFoundation.AnatomyEngine.Geometry.Hemisphere, and FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Renderable.UVMesh.UVMesh().
GenerateMesh()
virtual UVMesh FreedomOfFormFoundation.AnatomyEngine.Geometry.Surface.GenerateMesh (int resolutionU, int resolutionV, int indexOffset = 0) inline virtual
Generates the vertex positions and indices of this uv-parametrized surface. The returned list will contain approximately resolutionU times resolutionV vertices in total. The meaning of the coordinates u and v depends on the specific type of surface.
Definition at line 38 of file Surface.cs.
         {
             return new UVMesh(this, resolutionU, resolutionV, indexOffset);
         }
GenerateVertexList()
abstract List<Vertex> FreedomOfFormFoundation.AnatomyEngine.Geometry.Surface.GenerateVertexList (int resolutionU, int resolutionV) pure virtual
Generates the vertex positions of this uv-parametrized surface. The returned list will contain approximately resolutionU times resolutionV vertices in total. The meaning of the coordinates u and v depends on the specific type of surface.
Implemented in FreedomOfFormFoundation.AnatomyEngine.Geometry.Hemisphere, and FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Renderable.UVMesh.UVMesh().
GetNormalAt()
abstract Vector3 FreedomOfFormFoundation.AnatomyEngine.Geometry.Surface.GetNormalAt (Vector2 uv) pure virtual
Returns the surface normal at the uv coordinate given.
Implemented in FreedomOfFormFoundation.AnatomyEngine.Geometry.Hemisphere, and FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Calculus.MoldCastMap.GetValueAt().
GetPositionAt()
abstract Vector3 FreedomOfFormFoundation.AnatomyEngine.Geometry.Surface.GetPositionAt (Vector2 uv) pure virtual
Returns the surface position at the uv coordinate given.
Implemented in FreedomOfFormFoundation.AnatomyEngine.Geometry.Hemisphere, and FreedomOfFormFoundation.AnatomyEngine.Geometry.Cylinder.
Referenced by FreedomOfFormFoundation.AnatomyEngine.Calculus.MoldCastMap.GetValueAt().
The documentation for this class was generated from the following file:
engine/geometry/Surface.cs